apiVersion: apps/v1
kind: Deployment
metadata:
  name: stock-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stock-api
  template:
    metadata:
      labels:
        app: stock-api
    spec:
      securityContext:
        fsGroup: 2000

      containers:
        - name: stock-api
          image: widgetario/stock-api:21.03
          ports:
            - containerPort: 8080
          env:
            - name: POSTGRES_CONNECTION_STRING
              value: "postgres://postgres:SuperSecret123@products-db-1.products-db.default.svc.cluster.local:5432/products"
          volumeMounts:
            - name: cache-volume
              mountPath: /cache

          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5

          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          securityContext:
            runAsUser: 1000
            runAsGroup: 3000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

      volumes:
        - name: cache-volume
          emptyDir: {}

