apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: widgetario/web:21.03
          ports:
            - containerPort: 80
          env:
            - name: Widgetario__Theme
              value: dark
          volumeMounts:
            - name: secrets-volume
              mountPath: /app/secrets/api.json
              subPath: api.json
      volumes:
        - name: secrets-volume
          configMap:
            name: web-secrets
